"""Random-stream owner orders of the features-off draw paths (#28).

A compiled draw function reseeds one stream per random variable: ``reseed_rngs``
hands stream ``i`` of a single ``SeedSequence(...).spawn(n)`` to the ``i``-th RNG
of the list ``world_model._get_cached_draw_fn`` builds. That list, named by each
RNG's random variable, therefore decides every seeded draw. :func:`reseeded_order`
rebuilds it the same way, from the draw names that real ``draw_worlds`` calls
request, with only APIs that main (ce068d5) shares with this tree.

``tests/test_rng_owner_contract.py`` compares this tree's orders with the ones
recorded from main in ``tests/_rng_owner_baseline.py``. Running this file as a
script prints that module; its header gives the regeneration command.
"""

from __future__ import annotations

import contextlib
import json
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import numpy as np
from pymc.pytensorf import collect_default_updates

import pymc_generator as pg
from pymc_generator import world_model
from pymc_generator.sampler import (
    _ADDITIVE_OUT_NAMES,
    _CORPUS_PARAM_NAMES,
    _CORPUS_SHOCK_NAMES,
    CARRYOVER_FAMILY_KEYS,
    SATURATION_FAMILY_KEYS,
    _slice_g_active,
    sample_g_additive,
)
from pymc_generator.world_model_template import build_cell_inputs, build_world_model_template

BASELINE_SHA = "ce068d598fc0438b511c265ef09d7ba33354cb48"

#: ``(out_names, rng_reference_names)`` of one ``draw_worlds`` call; ``()`` means no reference.
Request = tuple[tuple[str, ...], tuple[str, ...]]

#: The features-off corpus draw names, which the template draws too.
CORPUS_NAMES = _CORPUS_PARAM_NAMES + _CORPUS_SHOCK_NAMES + _ADDITIVE_OUT_NAMES

#: d33ded9's probe layout: 2 treatments, 1 covariate, 1 latent, 16 weeks.
PROBE: dict[str, Any] = {"n_treatments": 2, "n_covariates": 1, "n_latent": 1, "n_time_steps": 16}

#: Every carryover x saturation family pair, keyed ``"carryover/saturation"``.
PAIRS = tuple(f"{c}/{s}" for c in CARRYOVER_FAMILY_KEYS for s in SATURATION_FAMILY_KEYS)

#: Template layouts: the default graph, every saturation family with padded
#: slots, and texture off under absolute outcome noise.
TEMPLATES: dict[str, dict[str, Any]] = {
    "probe": {
        "n_treatments": 3,
        "n_covariates": 2,
        "n_latent": 1,
        "n_time_steps": 24,
        "n_cells": 3,
        "seed": 11,
        "confounding_strength_range": (0.3, 0.3),
    },
    "active_all_families": {
        "n_treatments": 5,
        "n_covariates": 4,
        "n_latent": 2,
        "n_time_steps": 30,
        "n_cells": 6,
        "seed": 5,
        "n_treatments_active_range": (2, 5),
        "n_covariates_active_range": (1, 4),
        "n_latent_active_range": (1, 2),
        "saturation_family_probs": dict.fromkeys(
            SATURATION_FAMILY_KEYS, 1.0 / len(SATURATION_FAMILY_KEYS)
        ),
    },
    "texture_off_absolute": {
        "n_treatments": 4,
        "n_covariates": 3,
        "n_latent": 1,
        "n_time_steps": 20,
        "n_cells": 4,
        "seed": 21,
        "outcome_std_mode": "absolute",
        **dict.fromkeys(
            (
                "treatment_hf_sigma_range",
                "treatment_pulse_prob_range",
                "covariate_hf_sigma_range",
                "covariate_pulse_prob_range",
                "covariate_pulse_amp_range",
            ),
            (0.0, 0.0),
        ),
    },
}

_HEADER = f'''"""Main's random-stream owner orders; generated by ``tests/_rng_owners.py``, do not edit.

Recorded from main {BASELINE_SHA}. Regenerate from a
neutral directory, with that commit checked out at ``$MAIN`` and this repository
at ``$REPO``::

    cd /tmp && OUT="$REPO/tests/_rng_owner_baseline.py"
    PYTHONPATH="$MAIN" "$REPO/.venv/bin/python" "$REPO/tests/_rng_owners.py" >"$OUT"

This tree must keep every order, so the same command with ``PYTHONPATH="$REPO"``
reproduces this file byte for byte.
"""
'''


@contextlib.contextmanager
def capture_requests() -> Iterator[list[Request]]:
    """Record the request of every ``draw_worlds`` call made inside the block, in order.

    The corpus loop and ``sample_scm`` import ``draw_worlds`` from
    ``pymc_generator.world_model`` when they run, at main and here, so replacing
    that attribute sees their calls. Every call is passed through unchanged.
    """
    requests: list[Request] = []
    real = world_model.draw_worlds

    def recording(model, out_names, *args, **kwargs):
        requests.append((tuple(out_names), tuple(kwargs.get("rng_reference_names") or ())))
        return real(model, out_names, *args, **kwargs)

    world_model.draw_worlds = recording
    try:
        yield requests
    finally:
        world_model.draw_worlds = real


def single_request(requests: list[Request]) -> Request:
    """The one request every call in ``requests`` made."""
    distinct = set(requests)
    if len(distinct) != 1:
        raise AssertionError(f"expected one distinct draw request, got {len(distinct)}")
    return distinct.pop()


def corpus_request(**overrides: Any) -> Request:
    """What a two-cell probe corpus requests (``n_cells=1`` is rejected at both commits)."""
    cfg = pg.make_scm_prior(**PROBE, n_cells=2, draws_per_cell=1, **overrides)
    with capture_requests() as requests:
        pg.sample_prior_predictive(cfg)
    return single_request(requests)


def world_request(**overrides: Any) -> Request:
    """What ``sample_scm`` requests for the probe layout at seed 0."""
    cfg = pg.make_scm_prior(**PROBE, **overrides)
    with capture_requests() as requests:
        pg.sample_scm(cfg, seed=0)
    return single_request(requests)


def reseeded_order(
    model, out_names: tuple[str, ...], rng_reference_names: tuple[str, ...]
) -> tuple[str, ...]:
    """Random-variable names in the order a draw of ``out_names`` reseeds their RNGs.

    As in ``_get_cached_draw_fn``: the RNGs the reference reaches come first, in
    PyMC's traversal order, then those only ``out_names`` reach. Without a
    reference the order is the outputs' traversal alone.
    """
    owner = {rv.owner.inputs[0]: rv.name for rv in model.basic_RVs}
    with model:
        outputs = [model[name] for name in out_names]
        reference = [model[name] for name in rng_reference_names]
    rngs = list(collect_default_updates(inputs=[], outputs=outputs))
    if reference:
        reached = list(collect_default_updates(inputs=[], outputs=reference))
        rngs = reached + [rng for rng in rngs if rng not in reached]
    unowned = [rng for rng in rngs if rng not in owner]
    if unowned:
        raise AssertionError(f"{len(unowned)} reseeded RNGs belong to no model random variable")
    return tuple(owner[rng] for rng in rngs)


def probe_cell() -> dict[str, np.ndarray]:
    """d33ded9's probe cell: the covariate feeds both treatments, treatment 0 feeds 1."""
    return {
        "g_cy": np.array([1, 1]),
        "g_dc": np.zeros((1, 2), dtype=int),
        "g_dz": np.zeros((1, 1), dtype=int),
        "g_dy": np.ones(1, dtype=int),
        "g_zy": np.ones(1, dtype=int),
        "g_zc": np.ones((1, 2), dtype=int),
        "g_cc": np.array([[0, 1], [0, 0]]),
        "g_zz": np.zeros((1, 1), dtype=int),
    }


def probe_model(cfg, carry: str, sat: str):
    """The probe cell's world model with both treatments on families ``carry`` and ``sat``.

    The remaining structure is ``sample_structure`` at ``default_rng(0)``.
    """
    g = probe_cell()
    structural = world_model.sample_structure(g, cfg, np.random.default_rng(0))
    structural["carryover_family"][:] = CARRYOVER_FAMILY_KEYS.index(carry)
    structural["sat_family"][:] = SATURATION_FAMILY_KEYS.index(sat)
    model, _, _ = world_model.build_world_model(g, cfg, structural, cfg.n_time_steps)
    return model


def probe_order(cfg, pair: str, request: Request) -> tuple[str, ...]:
    """:func:`reseeded_order` of ``request`` on the probe model of ``pair``."""
    carry, sat = pair.split("/")
    return reseeded_order(probe_model(cfg, carry, sat), *request)


def template_model(cfg):
    """The template model, initialised with the benchmark workload's first cell.

    Restates ``make_workload`` in ``benchmarks/template_vs_per_world.py`` (the
    same at both commits). Cell values only initialise ``pm.Data``; the graph,
    and so the order, depends on the config alone.
    """
    rng = np.random.default_rng(cfg.seed)
    counts = [
        int(rng.integers(lo, hi + 1))
        for lo, hi in (
            cfg.n_treatments_active_range_effective,
            cfg.n_covariates_active_range_effective,
            cfg.n_latent_active_range_effective,
        )
    ]
    g = sample_g_additive(rng, cfg, cfg.layout, *counts)
    structure = world_model.sample_structure(_slice_g_active(g, *counts), cfg, rng)
    inputs = build_cell_inputs(cfg, g, g, structure)
    model, _, _ = build_world_model_template(cfg, inputs, cfg.n_time_steps)
    return model


def template_order(name: str) -> tuple[str, ...]:
    """The template draw function's order for config ``name`` (corpus names, no reference)."""
    return reseeded_order(template_model(pg.make_scm_prior(**TEMPLATES[name])), CORPUS_NAMES, ())


def record() -> dict[str, dict[str, tuple[str, ...]]]:
    """Every pinned order, measured on the tree ``pymc_generator`` was imported from."""
    probe = pg.make_scm_prior(**PROBE)
    corpus, world = corpus_request(), world_request()
    shocked = pg.make_scm_prior(**PROBE, n_treatment_shocks=1)
    shock_corpus = corpus_request(n_treatment_shocks=1)
    return {
        "ORDINARY": {pair: probe_order(probe, pair, corpus) for pair in PAIRS},
        "SINGLE_WORLD": {pair: probe_order(probe, pair, world) for pair in PAIRS},
        "SHOCKS": {"weibull/hill": probe_order(shocked, "weibull/hill", shock_corpus)},
        "TEMPLATE": {name: template_order(name) for name in TEMPLATES},
    }


def package_files() -> dict[str, Path]:
    """The resolved source file of every loaded ``pymc_generator`` module."""
    return {
        name: Path(module.__file__).resolve()
        for name, module in list(sys.modules.items())
        if name == "pymc_generator" or name.startswith("pymc_generator.")
    }


def baseline_module(orders: dict[str, dict[str, tuple[str, ...]]]) -> str:
    """``tests/_rng_owner_baseline.py`` for ``orders``, one name per line, ruff-format stable."""
    lines = [_HEADER]
    for constant, table in orders.items():
        lines.append(f"{constant}: dict[str, tuple[str, ...]] = {{")
        for key, names in table.items():
            lines.append(f"    {json.dumps(key)}: (")
            lines.extend(f"        {json.dumps(name)}," for name in names)
            lines.append("    ),")
        lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> None:
    """Print the baseline module measured on the imported tree, after checking it is one tree."""
    orders = record()
    root = Path(pg.__file__).resolve().parent
    files = package_files()
    stray = {name: str(path) for name, path in files.items() if not path.is_relative_to(root)}
    if stray:
        raise SystemExit(f"pymc_generator modules imported from outside {root}: {stray}")
    print(f"recorded from {root}", file=sys.stderr)
    sys.stdout.write(baseline_module(orders))


if __name__ == "__main__":
    main()
